# Save this as import_hospitals.py in your Django project

data = """KITUI COUNTY REFERRAL HOSPITAL,KITUI,LEVEL 4,PUBLIC
BORDER POLICE HOSPITAL,KITUI,LEVEL 4,PUBLIC
KATHIANI SUB-COUNTY HOSPITAL,MACHAKOS,LEVEL 4,PUBLIC
KANGUNDO SUB-COUNTY HOSPITAL,MACHAKOS,LEVEL 4,PUBLIC
TAWA SUB-COUNTY HOSPITAL,MAKUENI,LEVEL 4,PUBLIC
KISAU SUB-COUNTY HOSPITAL,MAKUENI,LEVEL 4,PUBLIC
MATILIKU SUB-COUNTY HOSPITAL,MAKUENI,LEVEL 4,PUBLIC
SULTAN HAMUD SUB COUNTY HOSPITAL,MAKUENI,LEVEL 4,PUBLIC
MAKUENI COUNTY REFERRAL HOSPITAL,MAKUENI,LEVEL 4,PUBLIC
MACHAKOS LEVEL 5 HOSPITAL,MACHAKOS,LEVEL 5,PUBLIC
THE KITUI HOSPITAL,KITUI,LEVEL 4,PRIVATE
NEEMA HOSPITAL LTD,KITUI,LEVEL 4,PRIVATE
CITY GATE DOCTORS PLAZA LTD,KITUI,LEVEL 4B,PRIVATE
NEEMA HOSPITAL LTD ANNEX,KITUI,LEVEL 4,PRIVATE
DOSAGE MEDICAL CENTRE,KITUI,LEVEL 4,PRIVATE
MWINGI SPECIALIST HOSPITAL,KITUI,LEVEL 4,PRIVATE
DOCTORS CENTRE-KITUI,KITUI,LEVEL 4,PRIVATE
MWINGI MEDICARE CENTRE-LTD,KITUI,LEVEL 4,PRIVATE
MACHAKOS IMAGING CENTRE LTD-MWINGI,KITUI,LEVEL 4B,PRIVATE
SHALOM HOSPITAL,MACHAKOS,LEVEL 4,PRIVATE
ATHI RIVER SHALOM COMMUNITY HOSPITAL,MACHAKOS,LEVEL 4,PRIVATE
LIFESPRINGS HEALTHCARE LIMITED,MACHAKOS,LEVEL 4,PRIVATE
MACHAKOS DOCTORS PLAZA LTD,MACHAKOS,LEVEL 4,PRIVATE
BRISTOL PARK HOSPITAL MACHAKOS,MACHAKOS,LEVEL 4,PRIVATE
RFH HEALTHCARE - SYOKIMAU,MACHAKOS,LEVEL 4,PRIVATE
THE VETERAN MISSION HOSPITALS LIMITED,MACHAKOS,LEVEL 4,PRIVATE
ULTRA KATHIANI HOSPITAL LIMITED,MACHAKOS,LEVEL 4,PRIVATE
KATANI HOSPITAL LIMITED,MACHAKOS,LEVEL 4,PRIVATE
RELIABLE HEALTHCARE SERVICES LIMITED,MACHAKOS,LEVEL 4,PRIVATE
SANEL HOSPITAL LIMITED,MACHAKOS,LEVEL 4,PRIVATE
PLAZA SPECIALIST HOSPITAL LIMITED,MACHAKOS,LEVEL 4,PRIVATE
THE MATUU HOSPITAL LIMITED,MACHAKOS,LEVEL 4,PRIVATE
MULATYA MEMORIAL HOSPITAL,MAKUENI,LEVEL 4,PRIVATE
MAKINDU MEDICAL CENTRE,MAKUENI,LEVEL 4,PRIVATE
KILOME MNH HOSPITAL,MAKUENI,LEVEL 4,PRIVATE
THE MAKUENI DOCTORS PLAZA LIMITED,MAKUENI,LEVEL 4,PRIVATE
ROYALSTAR FAMILY HOSPITAL LIMITED,MAKUENI,LEVEL 4,PRIVATE
BESTCARE HOSPITAL LIMITED,MAKUENI,LEVEL 4,PRIVATE
THE FORK HOSPITAL KENYA,MACHAKOS,LEVEL 5,PRIVATE
UNIVERSAL FAMILY HEALTH SERVICES,MACHAKOS,LEVEL 5,PRIVATE
JORDAN HOSPITAL,KITUI,LEVEL 5,PRIVATE"""

def import_hospitals():
    from .models import Hospital  
    
    # Clear existing data if needed
    # Hospital.objects.all().delete()
    
    hospitals_created = 0
    for line in data.split('\n'):
        name, location, level, ownership = line.strip().split(',')
        
        Hospital.objects.create(
            name=name,
            location=location,
            level=level,
            ownership=ownership
        )
        hospitals_created += 1
    
    print(f"Successfully created {hospitals_created} hospitals")

# To run in Django shell:
# from import_hospitals import import_hospitals
# import_hospitals()