FROM node:16-slim

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g yarn

VOLUME ["/data"]

COPY docker-entrypoint-node.sh /
ENTRYPOINT ["/docker-entrypoint-node.sh"]