FROM rdrf-base

COPY build/dist/*.tar.gz /data/
RUN tar xvf /data/*.tar.gz -C /app \
    && rm /data/*.tar.gz

WORKDIR /app/rdrf

ENV PATH="/app/rdrf/bin:${PATH}" \
    PYTHONPATH="/app/rdrf/rdrf:/app/rdrf:${PYTHONPATH}"

COPY docker-entrypoint-prod.sh /
ENTRYPOINT ["/docker-entrypoint-prod.sh"]