FROM rdrf-base

WORKDIR /app

# Copy the application source
COPY . /app/rdrf

# Install dependencies from requirements.txt instead of setup.py
COPY requirements.txt /app/
RUN pip install -r requirements.txt

VOLUME ["/data"]

ENV PATH="/app/bin:${PATH}" \
  PYTHONPATH="/app/rdrf/rdrf:/app/rdrf:${PYTHONPATH}"

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]