# Generated by Django 3.2.15 on 2024-12-13 00:49

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0040_auto_20211108_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAdditionalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', django_jsonform.models.fields.JSONField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
