# Generated by Django 3.2.15 on 2024-12-13 00:59

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0041_patientadditionalform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientadditionalform',
            name='values',
        ),
        migrations.AddField(
            model_name='patientadditionalform',
            name='definition',
            field=models.JSONField(default={}),
        ),
        migrations.CreateModel(
            name='PatientAdditionalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django_jsonform.models.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientadditionalform')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
