# Generated by Django 3.2.15 on 2024-12-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0042_auto_20241213_0059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientAdditionalForm',
            new_name='PatientCustomForm',
        ),
        migrations.RenameModel(
            old_name='PatientAdditionalData',
            new_name='PatientCustomFormData',
        ),
    ]
