# Generated by Django 3.2.15 on 2024-12-21 23:11

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0043_auto_20241213_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schema', django_jsonform.models.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patientcustomform',
            name='definition',
            field=django_jsonform.models.fields.JSONField(default={}),
        ),
    ]
