# Generated by Django 3.2.15 on 2024-12-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0044_auto_20241221_2311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientCustomFormData',
        ),
    ]
