# Generated by Django 3.2.15 on 2024-12-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0045_delete_patientcustomformdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='National Id/Passport'),
        ),
    ]
