# Generated by Django 3.2.15 on 2024-12-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0046_patient_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], max_length=255, null=True, verbose_name='Marital Status'),
        ),
    ]
