# Generated by Django 3.2.15 on 2024-12-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0048_auto_20241224_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaddress',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='address_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.addresstype', verbose_name='Address type'),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='state',
            field=models.CharField(max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Suburb/Town'),
        ),
    ]
