# Generated by Django 3.2.15 on 2024-12-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0049_auto_20241224_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_of_kin_state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='County'),
        ),
    ]
