# Generated by Django 3.2.15 on 2025-02-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0050_alter_patient_next_of_kin_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='family_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='given_names',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Last Name'),
        ),
    ]
