# Generated by Django 3.2.15 on 2025-02-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_auto_20181220_1457'),
        ('patients', '0051_auto_20250203_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ownership',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='working_groups',
            field=models.ManyToManyField(help_text='You must only select one Registry to save a patient.', related_name='my_patients', to='groups.WorkingGroup', verbose_name='Registry'),
        ),
    ]
