# Generated by Django 3.2.15 on 2025-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0052_auto_20250212_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaddress',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Village/State'),
        ),
    ]
