# Generated by Django 3.2.15 on 2025-03-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0053_alter_patientaddress_suburb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaddress',
            name='address_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.addresstype', verbose_name='Address type'),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Landmark'),
        ),
    ]
