# Generated by Django 3.2.15 on 2025-03-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0054_auto_20250324_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='parity',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True, verbose_name='Parity'),
        ),
    ]
