# Generated by Django 3.2.15 on 2025-04-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0055_patient_parity'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsent',
            name='allow_for_follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
