# Generated by Django 3.2.15 on 2025-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0056_patientconsent_allow_for_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsent',
            name='allow_for_storage',
            field=models.BooleanField(default=False, verbose_name='Is the patient able and willing to allow his/her personal data to be added in this registry, and stored until such a time he/she withdraws consent/permission?'),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='allow_for_follow_up',
            field=models.BooleanField(default=False, verbose_name='Is the patient willing to be contacted for follow-up and further assessment? Y/N'),
        ),
    ]
