# Generated by Django 3.2.15 on 2024-12-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0145_auto_20220914_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPseudonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(blank=True, max_length=255, null=True)),
                ('original_patient_record', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
