# Generated by Django 3.2.15 on 2024-12-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0146_create_patientpseudonym_pseudonyms'),
        ('rdrf', '0146_patientpseudonym'),
    ]

    operations = [
    ]
