# Generated by Django 3.2.15 on 2024-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0147_merge_20241212_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpseudonym',
            name='patient_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientpseudonym',
            name='patient_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
