# Generated by Django 3.2.15 on 2024-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0148_auto_20241212_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpseudonym',
            name='original_patient_record',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
