# Generated by Django 3.2.15 on 2024-12-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0149_alter_patientpseudonym_original_patient_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpseudonym',
            name='original_patient_record',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
