# Generated by Django 3.2.15 on 2024-12-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0150_alter_patientpseudonym_original_patient_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_custom_form',
            field=models.BooleanField(default=False),
        ),
    ]
