# Generated by Django 3.2.15 on 2024-12-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0152_customformdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryform',
            name='sections',
            field=models.TextField(help_text='Comma-separated list of sections, as defined in The Section Forms'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name (same as form in formIo)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='elements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
