# Generated by Django 3.2.15 on 2025-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0153_auto_20241224_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformdata',
            name='visit_number',
            field=models.IntegerField(default=1),
        ),
    ]
